upstream labcamp_app { server app:3000; }

server {
  listen 80;
  listen [::]:80;
  server_name labcamp.duckdns.org;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}
